### ISSUE TITLE
Incorrectly Rendered Board Outline

### ISSUE THREAD

**Issue by metacollin** [tracespace/tracespace#409] opened 2023-01-21 19:51 UTC
This board outline:
![jmLtiLm7QkUM](https://user-images.githubusercontent.com/181882/213884662-295851a5-a9b5-4f04-adcc-c582ee725536.png)

Is rendered as this in tracespace:
![9pktKhnxibZj](https://user-images.githubusercontent.com/181882/213884678-a2e05b1b-9af8-4f6a-86e3-7e1a9e64958c.png)

Here is the gerber. Nothing exotic or weird going on inside. 
[outline.gbr.zip](https://github.com/tracespace/tracespace/files/10472903/outline.gbr.zip)

I would note that it correctly renders the gerber path otherwise. The issue only occurs when that path ends up getting used as a clip-path. The order of the pen moves seems strange and may not work correctly when used as a clip path.

**Comment by mcous** [comment] 2023-01-22 00:02
Thanks for the example file @metacollin! I think this is happening because there are 5 small gaps of about 0.005" in the outline layer itself, between:

- `0.019901, 11.023241` and `0.015, 11.023`
- `0.019901, 11.522759` and `0.015, 11.522999`
- `13.740099, 6.774759` and `13.745, 6.774999`
- `13.695241, 6.570099` and `13.695, 6.575`
- `13.745, 6.525` and `13.740099, 6.525241`

Those gaps are almost certainly where you see those streaks going across the board shape.

Given that the gaps are all the exact same size of 5 mils, I expect this is probably due to the drawing grid in your CAD software. It could also be an issue with how your CAD exports Gerber. The "arcs" on the corners, for example, are all approximated as line segments rather than Gerber arcs.

In the tracespace viewer, you can increase the "gap fill limit" setting to render this board correctly:

<img width="736" alt="Screen Shot 2023-01-21 at 6 48 13 PM" src="https://user-images.githubusercontent.com/2963448/213894484-37ee1bae-3308-4e03-93a2-3d33eb7a0ae9.png">

I ran this outline file through the v5 board shape plotter and thankfully it processed without issue. The v5 render logic does a few things differently than the currently released version, including:

- Much higher default limit for the largest gap it's willing to fill
- Paths with gaps will be rejected as an outline, and thus will not be placed in a `clipPath`

Since this is expected behavior for the currently released v4, and is fixed in v5, I'm going to close this issue. Do you mind if I use this outline Gerber file (with attribution) as a part of the v5 board shape test suite?

**Closed as completed by mcous** 2023-01-22 00:02 UTC
Labels: v5-fixed, board-shape
